Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    chunk_start, chunk_end = split_file_into_chunks(twitter_file, size)
  File "/home/sunchuangyuh/A1/scripts/utils.py", line 29, in split_file_into_chunks
    file_size: int = path.stat().st_size
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/pathlib.py", line 1168, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: 'data/bigTwitter'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[3476,1],4]
  Exit code:    1
--------------------------------------------------------------------------
