Traceback (most recent call last):
  File "main.py", line 38, in <module>
    sal_df = load_sal_csv(PATH, logger)
  File "/home/sunchuangyuh/A1/scripts/sal_processor.py", line 88, in load_sal_csv
    df = pd.read_csv(sal_file)
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/sunchuangyuh/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
slurmstepd: error: *** JOB 45932629 ON spartan-bm095 CANCELLED AT 2023-03-30T18:08:57 ***
